# Generated by Django 5.1.4 on 2025-01-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='a_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
