# Generated by Django 5.1.4 on 2025-01-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_visitor_a_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='a_count',
        ),
    ]
