# Generated by Django 5.1.4 on 2024-12-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schdl', '0002_bhp_created_at_lhp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lhp',
            name='created_at',
        ),
        migrations.AddField(
            model_name='bhp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lhp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
