# Generated by Django 5.1.4 on 2025-01-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schdl', '0003_remove_bhp_created_at_remove_lhp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhp',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lhp',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
