# Generated by Django 5.1.4 on 2025-01-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schdl', '0004_bhp_public_id_lhp_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhp',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='lhp',
            name='public_id',
        ),
    ]
