# Generated by Django 5.1.4 on 2025-01-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schdl', '0005_remove_bhp_public_id_remove_lhp_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhp',
            name='pbid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lhp',
            name='pbid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
